const express = require("express");
const app = express();
const port = process.env.PORT || 4000;
app.listen(port, () => console.log(`Listening on port ${port}`));
const db = require("./db");
const Image = require("./image/model");
const cors = require("cors");
const corsMiddleware = cors();
const parser = require("body-parser");
const parserMiddleware = parser();
const imageRouter = require("./image/router");
app.use(corsMiddleware);
app.use(parserMiddleware);
app.use(imageRouter);
